### ISSUE TITLE
Add seeking

### ISSUE THREAD

**Issue by keratagpro** [keratagpro/tagpro-vcr#6]
Right now, the recorder just stores every packet that is sent from the server to the browser. To seek to a given point in time, you would actually need to replay all the packets from 0 to that point to get the correct global game state.

A viable solution might be to store a snapshot of the global game state (player positions, player powerups, bomb/powerup/portal states etc.) in the recording every N seconds. This way the VCR webpage could find the latest snapshot for any given time and replay the packets from that point forward. This is similar to how video codecs work (see [I-frames](https://en.wikipedia.org/wiki/Video_compression_picture_types#Summary)).

**Comment by bash-tp** [comment]
PR #3 adds the seek feature as well, by replaying all packets. This turns out to work surprisingly well and it's fast enough that keyframes shouldn't be necessary!
